package vista;

import controlador.ControllerProducto;
import controlador.ControllerProveedor;
import controlador.ControllerUsuario;
import helpers.Helpers;

public final class frmPaginaPrincipal extends javax.swing.JFrame {

    Helpers helpers = new Helpers();

    /**
     * Creates new form frmPaginaPrincipal
     *
     * @param idUsuario
     * @param nombreUsuario
     * @param tipoUsuario
     */
    public frmPaginaPrincipal(String idUsuario, String nombreUsuario, String tipoUsuario) {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("SISTEMA VENTAS DE AUTOS");
        lblIdUsuario.setText(idUsuario);
        lblNombreUsuario.setText(nombreUsuario);
        lblTipoUsuario.setText(tipoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblIdUsuario = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuCatalogoDatos = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenuItem();
        btnProveedores = new javax.swing.JMenuItem();
        MenuProcesos = new javax.swing.JMenu();
        btnProductos = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        btnProductosPorFechaCaducidad = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        btnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmPaginaPrincipal"); // NOI18N

        lblIdUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblIdUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIdUsuario.setText("ID de Usuario");
        desktopPane.add(lblIdUsuario);
        lblIdUsuario.setBounds(20, 20, 200, 20);

        lblTipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipoUsuario.setText("Tipo de Usuario");
        desktopPane.add(lblTipoUsuario);
        lblTipoUsuario.setBounds(20, 80, 200, 20);

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombreUsuario.setText("Nombre Usuario");
        desktopPane.add(lblNombreUsuario);
        lblNombreUsuario.setBounds(20, 50, 200, 20);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuCatalogoDatos.setMnemonic('e');
        menuCatalogoDatos.setText("Catálogo de Datos");

        btnUsuarios.setMnemonic('t');
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnUsuarios);

        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        menuCatalogoDatos.add(btnProveedores);

        menuBar.add(menuCatalogoDatos);

        MenuProcesos.setText("Procesos");
        MenuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProcesosActionPerformed(evt);
            }
        });

        btnProductos.setText("Inventario de productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        MenuProcesos.add(btnProductos);

        menuBar.add(MenuProcesos);

        menuReportes.setText("Reportes");

        btnProductosPorFechaCaducidad.setText("Productos por fechas de caducidad");
        btnProductosPorFechaCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosPorFechaCaducidadActionPerformed(evt);
            }
        });
        menuReportes.add(btnProductosPorFechaCaducidad);

        menuBar.add(menuReportes);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        btnAbout.setMnemonic('a');
        btnAbout.setText("About");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        helpMenu.add(btnAbout);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        frmUsuario obj = new frmUsuario();
        desktopPane.add(obj);
        ControllerUsuario con = new ControllerUsuario(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        helpers.abrirArchivo("./docs/manual.pdf");
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        frmProveedor obj = new frmProveedor();
        desktopPane.add(obj);
        ControllerProveedor con = new ControllerProveedor(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void MenuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProcesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuProcesosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        frmProducto obj = new frmProducto();
        desktopPane.add(obj);
        ControllerProducto con = new ControllerProducto(obj);
        con.iniciar();
        obj.toFront();
        obj.setLocation(desktopPane.getWidth() / 2 - obj.getWidth() / 2, desktopPane.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnProductosPorFechaCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosPorFechaCaducidadActionPerformed

    }//GEN-LAST:event_btnProductosPorFechaCaducidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPaginaPrincipal(lblIdUsuario.getText(), lblNombreUsuario.getText(), lblTipoUsuario.getText()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuProcesos;
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JMenuItem btnProductos;
    private javax.swing.JMenuItem btnProductosPorFechaCaducidad;
    private javax.swing.JMenuItem btnProveedores;
    private javax.swing.JMenuItem btnUsuarios;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCatalogoDatos;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables

}
